version: "3.3"

services:
  api:
    build: .
    command: python src/server.py
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    volumes:
      - .:/src
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

volumes:
  postgres_data:
